from feast import Entity, Feature, FeatureView, FileSource, ValueType
from datetime import timedelta

# 1. Entity: The physical Location (Geohash) we are predicting for
location = Entity(name="geohash", value_type=ValueType.STRING, description="Geohash ID")

# 2. Source: Parquet files generated by the Stream Consumer (Phase 1)
trace_stats_source = FileSource(
    path="/data/parquet/trace_stats.parquet",
    timestamp_field="event_timestamp",
    created_timestamp_column="created_timestamp",
)

# 3. Feature View: Aggregated stats for GMM/GNN
location_stats_fv = FeatureView(
    name="location_stats",
    entities=["geohash"],
    ttl=timedelta(days=365),
    features=[
        Feature(name="avg_parking_lat", dtype=ValueType.FLOAT),
        Feature(name="avg_parking_lon", dtype=ValueType.FLOAT),
        Feature(name="scan_density", dtype=ValueType.FLOAT),
        Feature(name="delivery_count", dtype=ValueType.INT64),
    ],
    batch_source=trace_stats_source,
    online=True,
    tags={"tier": "production"} 
)